# Creates the photobank role + database WITHOUT the postgres superuser password,
# by temporarily allowing passwordless LOCAL logins for 'postgres' (pg_hba.conf),
# then restoring the original config. MUST run in an elevated (admin) PowerShell.
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$dataDir = "C:\Program Files\PostgreSQL\18\data"
$pgHba = "$dataDir\pg_hba.conf"
$backup = "$dataDir\pg_hba.conf.photobank-backup"
$psql = "C:\Program Files\PostgreSQL\18\bin\psql.exe"
$service = "postgresql-x64-18"

$principal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Host "This script must run as Administrator. Right-click PowerShell -> Run as administrator." -ForegroundColor Red
    exit 1
}

# app password comes from .env (already generated by setup.ps1)
$envLine = Select-String -Path "$root\.env" -Pattern "://photobank:([^@]+)@" | Select-Object -First 1
if (-not $envLine) { Write-Host "Could not read app password from .env" -ForegroundColor Red; exit 1 }
$appPassword = $envLine.Matches[0].Groups[1].Value

Write-Host "Backing up pg_hba.conf and enabling temporary local trust for 'postgres'..." -ForegroundColor Cyan
Copy-Item $pgHba $backup -Force
$trustLines = @(
    "# TEMPORARY - added by photobank fix-db.ps1, removed automatically"
    "host    all    postgres    127.0.0.1/32    trust"
    "host    all    postgres    ::1/128         trust"
)
Set-Content -Path $pgHba -Value ($trustLines + (Get-Content $backup)) -Encoding ascii

try {
    Restart-Service $service
    Start-Sleep -Seconds 3

    Write-Host "Creating role and database..." -ForegroundColor Cyan
    $roleSql = "DO `$`$ BEGIN IF EXISTS (SELECT FROM pg_roles WHERE rolname='photobank') THEN ALTER ROLE photobank LOGIN PASSWORD '$appPassword'; ELSE CREATE ROLE photobank LOGIN PASSWORD '$appPassword'; END IF; END `$`$;"
    & $psql -U postgres -h localhost -v ON_ERROR_STOP=1 -c $roleSql
    if ($LASTEXITCODE -ne 0) { throw "Failed to create/update role" }

    $dbExists = & $psql -U postgres -h localhost -tAc "SELECT 1 FROM pg_database WHERE datname='photobank'"
    if ($dbExists -ne "1") {
        & $psql -U postgres -h localhost -v ON_ERROR_STOP=1 -c "CREATE DATABASE photobank OWNER photobank"
        if ($LASTEXITCODE -ne 0) { throw "Failed to create database" }
        Write-Host "Database 'photobank' created." -ForegroundColor Green
    } else {
        & $psql -U postgres -h localhost -c "ALTER DATABASE photobank OWNER TO photobank" | Out-Null
        Write-Host "Database 'photobank' already exists." -ForegroundColor Green
    }
} finally {
    Write-Host "Restoring original pg_hba.conf..." -ForegroundColor Cyan
    Copy-Item $backup $pgHba -Force
    Remove-Item $backup -Force
    Restart-Service $service
}

# sanity check with the app credentials (no trust needed anymore)
$env:PGPASSWORD = $appPassword
$ok = & $psql -U photobank -h localhost -d photobank -tAc "SELECT 1"
Remove-Item Env:\PGPASSWORD -ErrorAction SilentlyContinue
if ($ok -eq "1") {
    Write-Host "`nDatabase ready - app login verified. Auth config restored to original." -ForegroundColor Green
} else {
    Write-Host "`nSomething is still wrong - app login failed." -ForegroundColor Red
    exit 1
}
